language: cpp

sudo: false

dist: bionic

compiler:
  - g++

before_install:
  - sudo apt-get install graphviz
  - sudo apt-get install cmake
  - sudo apt-get install flex
  - wget http://ftp.gnu.org/gnu/bison/bison-3.4.2.tar.gz
  - tar -zxvf bison-3.4.2.tar.gz
  - cd bison-3.4.2/
  - sudo ./configure
  - sudo make
  - sudo make install
  - sudo ln -s /usr/local/bin/bison /usr/bin/bison
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
